{% set name = "rai-sdk" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rai_sdk-{{ version }}.tar.gz
  sha256: d75a77126cabd95b3b946631cf4de7a694e9a8f23e6946decd2f31cd3c07a518

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pandas >=2.0.0,<3.0.0     # [py>38]
    - protobuf >=3.20.3,<5.0.0
    - pyarrow >=10.0.0,<16.0.0
    - requests-toolbelt ==1.0.0

test:
  source_files:
    # test/test_integration.py uses GH secrets etc.
    - test/test_unit.py
  imports:
    - railib
    - railib.pb
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v test

about:
  home: https://relational.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "The RelationalAI Software Development Kit for Python"
  description: |
    The RelationalAI (RAI) SDK for Python enables developers to access
    the RAI REST APIs from Python.
  doc_url: https://docs.relational.ai/rkgms/sdk/python-sdk
  dev_url: https://github.com/RelationalAI/rai-sdk-python

extra:
  recipe-maintainers:
    - ifitchet
